### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by steveoh** [agrc/fire-business#2]
**This needs revision from DNR**

From the uploaded shapefile return the following statistics:
County = Private - City(if city exists)
City = Private acres within a city
Counties + City = Private ADMIN
County acres = all unincorporated private lands within the fire perimeter
City acres = all incorporated private lands
Also need to track acreages in multiple counties (frequent) and cities (rare).
…….
total acreage of polygon
total acreage of polygon split by state
acreage of intersection in utah
acreage of intersection of each land ownership ADMIN category in Utah
acreage of intersection of city versus county for the Private ADMIN category in Utah

We will be given a geodatabase with expected results for testing and verification at a later date.

**Comment by steveoh** [comment]
For the input fire, the total acres are 5295.48.
Admin: Private: 4055.99, Tribal: 176.79
Municipality: Ballard 1023.65, Roosevelt: 39.05
The admin acres, and any municipality acres, should add up to the total polygon acres.
County Acres: Duchesne: 2550.53, Uintah: 1505.46
The county acres should add up to the admin-Private acres
State: 5295.48

**Comment by newtonsaunders-gs** [comment]
Diagram: https://docs.google.com/a/goldsystems.com/drawings/d/1S3L6AhQXKJlYfZ4cBNmcSL5jI-M-TxTmbO0kMkEIlGg/edit?usp=sharing

**Comment by newtonsaunders-gs** [comment]
Sample JSON: https://docs.google.com/a/goldsystems.com/document/d/1u12QZXviyx9zjC7Ih-FtJsd0lIOdv9YtLToLCNvvR9A/edit?usp=sharing
